# Generated by Django 5.2 on 2025-04-14 02:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Curso",
        ),
    ]
