# Generated by Django 5.2 on 2025-04-14 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_delete_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="curso",
            field=models.CharField(
                choices=[("1", "Python"), ("2", "Django"), ("3", "JavaScript")],
                default=None,
                max_length=2,
            ),
            preserve_default=False,
        ),
    ]
