# Generated by Django 5.2 on 2025-04-16 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_alumno_curso"),
    ]

    operations = [
        migrations.AddField(
            model_name="alumno",
            name="fecha_anotado",
            field=models.DateField(null=True),
        ),
    ]
